#------------------------------------------------------------
# Values for this workshop.
#------------------------------------------------------------
# What kind of thing is this ("workshop")? #Don't Change
kind: "workshop"
# Is this a permanent page 'static' or a taught workshop 'dated'
delivery: "dated"

# Overall title for the Workshop.
# This variable is used to (optionally) add a title in the "jumbotron"
# (the grey box at the top of the page), and to the extra pages.
title: "Introduction to Research Computing"
form_title: "Introduction+to+Research+Computing" # This is required for the surveys

# Email address, no mailto:
email: "rsginfo@soton.ac.uk"
logo_site: "https://rsgsoton.net"

# For static delivery this section can all be ignored ==================================================================
# Specify the location of the workshop
venue: "Building 60, Innovation Space"           # name of location use "online" if online
address: "TBC"         # address of location or url of platform
platform-name: "Teams"   # name of online platform e.g. Teams, Zoom e.t.c
country: "gb"         # e.g. gb
language: "en"        # e.g. en
latitude: "50.909698"    # latitude of location (Soton: 50.909698)
longitude: "-1.404351"   # longitude of location (Soton: -1.404351)

# Specify the start and end date of the workshop
humandate: "30th - 31st January 2024"      # e.g. "6th August"
humantime: "13:00 - 16:30"      # e.g. "09:00-17:00"
startdate: 2024-01-30        # e.g. YYYY-MM-DD # This is required for the surveys NOTE: 1990-1-1 will not work
enddate: 2024-01-31         # e.g. YYYY-MM-DD

# Specify the details of the instructors and helpers
# Can be list, or single string
instructor:
  - "Sam Mangham"

instructor-email:
  - "s.mangham@soton.ac.uk"
  
helper:
  - "Harry Baker"
# ======================================================================================================================

# Details about the lessons
lessons:
  - title: Version Control with git
    gh-name: git-novice
    type: episode
    branch: main
    date: 30 January 2024
    start-time: 13:00
    order: 1

  - title: Software Project Management
    gh-name: project-novice
    type: episode
    branch: main
    date: 31 January 2024
    start-time: 13:00
    order: 2

###
# It is unlikely you need to modify the values below this line
###

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:slug

include:
  - _includes/rsg/

# If there is both an R and python official version of a curriculum
# (as listed on https://software-carpentry.org/lessons/ and
# https://datacarpentry.org/lessons/), change the
# value of the variable below ("flavor") to get the schedule and installation
# instructions updated accordingly (valid values are 'r' or 'python').
# Note: this is only for Data Carpentry and SWC at this time.
flavor: "python"

# If the workshop will be a lesson pilot (for a new official lesson or
# a lesson in The Carpentries Incubator), set pilot to "true".
pilot: false

# rsg: Custom Lessons from the Southampton-RSG-Training git-org
carpentry: "rsg"

# Sites.
amy_site: "https://amy.carpentries.org/"
carpentries_github: "https://github.com/carpentries"
carpentries_pages: "https://carpentries.github.io"
carpentries_site: "https://carpentries.org/"
dc_site: "https://datacarpentry.org"
example_repo: "https://github.com/carpentries/lesson-example"
example_site: "https://carpentries.github.io/lesson-example"
incubator: "https://github.com/carpentries-incubator/"
lc_site: "https://librarycarpentry.org/"
swc_github: "https://github.com/swcarpentry"
swc_pages: "https://swcarpentry.github.io"
swc_site: "https://software-carpentry.org"
template_repo: "https://github.com/carpentries/styles"
training_site: "https://carpentries.github.io/instructor-training"
workshop_repo: "https://github.com/carpentries/workshop-template"
workshop_site: "https://carpentries.github.io/workshop-template"
cc_by_human: "https://creativecommons.org/licenses/by/4.0/"

# Start time in minutes (0 to be clock-independent, 540 to show a start at 09:00 am).
start_time: 0

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page


# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin/
  - .Rproj.user/
  - .vendor/
  - vendor/
  - .docker-vendor/
  - submodules/

# Turn on built-in syntax highlighting.
highlighter: rouge

# Using the new jekyll remote themes
remote_theme: Southampton-RSG-Training/rsg-theme

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-target-blank
  - jekyll-github-metadata